/**
 * Œuvres du BookshelfDLE : seulement des titres que tout lecteur de manga ou de
 * webtoon connaît (adaptés en anime pour la plupart). La popularité MangaDex ne
 * suffit pas à les reconnaître : bien des isekai confidentiels y ont plus de
 * lecteurs que des classiques. Noms tels que dans le set (titre anglais), comparés
 * sans casse, accents ni ponctuation.
 */
export const FAMOUS_WORKS = [
  // Shōnen et seinen incontournables.
  'One Piece',
  'Jujutsu Kaisen',
  'Chainsaw Man',
  'Demon Slayer: Kimetsu no Yaiba',
  'Attack on Titan',
  'My Hero Academia',
  'Hunter x Hunter',
  'Black Clover',
  'One-Punch Man',
  'SPY×FAMILY',
  'Dandadan',
  'Kaiju No. 8',
  'Blue Lock',
  'Sakamoto Days',
  'Kagurabachi',
  'Gachiakuta',
  'Dr. Stone',
  'Fire Force',
  'TOKYO GHOUL',
  'Tokyo Revengers',
  'Vinland Saga',
  'Kingdom',
  'Golden Kamuy',
  'Made In Abyss',
  'Goodnight Punpun',
  'BEASTARS',
  'Land of the Lustrous',
  'Record of Ragnarok',
  'Goblin Slayer',
  'Wistoria: Wand and Sword',
  "JoJo's Bizarre Adventure: Part 7–Steel Ball Run - Digital Colored Comics",
  "JoJo's Bizarre Adventure, Part 8: JoJolion - Digital Colored Comics",
  'JoJo\'s Bizarre Adventure Part 9 - The JOJOLands',
  // Fantasy, isekai et aventure.
  "Frieren: Beyond Journey's End",
  'Delicious in Dungeon',
  'Witch Hat Atelier',
  'The Apothecary Diaries',
  'That Time I Got Reincarnated as a Slime',
  'Mushoku Tensei: Jobless Reincarnation',
  'The Eminence in Shadow',
  'The Rising of the Shield Hero',
  'Overlord',
  'The Saga of Tanya the Evil',
  'Re:Monster',
  'So I’m a Spider, So What?',
  'Tsukimichi: Moonlit Fantasy',
  'Arifureta: From Commonplace to World\'s Strongest',
  'Skeleton Knight in Another World',
  'Reincarnated as a Sword',
  'Campfire Cooking in Another World with My Absurd Skill',
  'The Misfit of Demon King Academy: History\'s Strongest Demon King Reincarnates and Goes to School with His Descendants',
  'How a Realist Hero Rebuilt the Kingdom',
  'Isekai Uncle',
  'Welcome to Demon School! Iruma-kun',
  'GATE: Where the JSDF Fought',
  'My Next Life as a Villainess: All Routes Lead to Doom!',
  'The Saint\'s Magic Power is Omnipotent',
  'I\'ve Been Killing Slimes for 300 Years and Maxed Out My Level',
  'Kuma Kuma Kuma Bear',
  'Tearmoon Empire',
  'Yona of the Dawn',
  // Comédies et romances.
  'My Dress-Up Darling',
  'Komi Can\'t Communicate',
  'Kaguya-sama: Love Is War',
  'Horimiya',
  'Don\'t Toy With Me, Miss Nagatoro!',
  'The Dangers in My Heart',
  'Call of the Night',
  'Alya Sometimes Hides Her Feelings in Russian',
  '【My Star】',
  'Rent-A-Girlfriend',
  'The Five Wedded Brides',
  'Fly Me to The Moon',
  'Teasing Master Takagi-san',
  'Uzaki-chan Wants to Hang Out!',
  'Shikimori\'s Not Just a Cutie',
  'The Angel Next Door Spoils Me Rotten',
  'My Love Story with Yamada-kun at Lv999',
  'Wotakoi: Love Is Hard for Otaku',
  'Miss Kobayashi\'s Dragon Maid',
  'Tomo-chan wa Onna no ko!',
  'Girlfriend, Girlfriend',
  'The 100 Girlfriends Who Really, Really, Really, Really, Really Love You',
  'Grand Blue Dreaming',
  'The Way of the Househusband',
  'Mieruko-chan',
  'Insomniacs After School',
  'Bloom into You',
  'ONIMAI: I\'m Now Your Sister!',
  'The Ice Guy and the Cool Girl',
  'The Helpful Fox Senko-san',
  'Blue Period',
  'Higehiro: After Being Rejected, I Shaved and Took in a High School Runaway',
  // Webtoons et manhua.
  'Solo Leveling',
  'Solo Leveling: Ragnarok',
  'Omniscient Reader\'s Viewpoint',
  'Tower of God',
  'The Greatest Estate Developer',
  'Eleceed',
  'Nano Machine',
  'The Remarried Empress',
  'The Legend of the Northern Blade',
  'The Second Coming of Gluttony',
  'Overgeared',
  'The Founder Of Diabolism',
  'Release That Witch',
  'Tales of Demons and Gods',
  'Martial Peak',
  'Return of the Frozen Player',
  'The Player Who Can\'t Level Up',
] as const

/** En dessous, la sélection ne suffit plus (set différent) : on la complète par les plus suivies. */
export const MIN_FAMOUS = 40
